---
title: "Relationship between Illusion Sensitivity and Inter-individual Characteristics: A Registered Report"
author: "*Dominique Makowski, An Shu Te, Stephanie Kirk, Ngoi Zi Liang, & S.H. Annabel Chen*"
output: html_document
bibliography: references.bib
---



# Abstract

Despite its long-standing history and importance in psychological research, the correlates of visual illusion sensitivity remain unclear. Previous studies provided evidence in favour of links with personality traits and psychopathological conditions, such as schizophrenia and autism. In this study, we aim to replicate the findings on personality and extend them to more theoretically targeted dispositional characteristics, such as schizotypal and autistic traits.

# Introduction

Visual illusions are beguiling stimuli that reveal how the brain integrates prior beliefs with incoming sensory evidence to inform our perception of reality [@carbon2014understanding]. While early research theorized a common mechanism underlying people's sensitivity to illusions [@halpern1999interindividual; @thurstone1944factorial], recent empirical studies reported at best weak correlations between inter-individual resistance to distinct illusions [@grzeczkowski2017individual;  @grzeczkowski2018perception]. This is a significant issue, as the existence of a common factor is evidence in support of the theoretical proposition that the effects of illusions are not mere artefacts caused by our perceptual system, but potential markers of a more general property of our cognitive systems.

The idea that visual illusions sensitivity reflects characteristics of the functioning at a general cognitive level is supported by evidence linking them to high-level features such as cognitive abilities [@chouinard2020strength; @liao2011poggendorff; @bednarekcognitive; @chouinard2016susceptibility], personality traits [@zhang2017personality; @konrath2009seeing; @blake2021divergent], and psychopathological disorders such as schizophrenia [@pessoa2008; @grzeczkowski2018; @notredame2014], autism [@park2022; @manning2017; @gori2016], and anxiety [@baroun2005impact; @passie2013impaired]. Interestingly, from the latter investigations stemmed theoretical proposals reframing the effect of illusions (and its varying inter-individual sensitivity) under Bayesian predictive coding accounts of the brain [@notredame2014; @gori2016]. Specifically, the Bayesian framework conceptualizes our perceptions of ambiguous stimuli as a culmination of our implicit knowledge, combined with incoming sensory information [@friston2010free]. In this context, sensitivity to illusions indexes the discrepancy between one's prior beliefs and incoming sensory evidence [@gershman2012multistability; @sundareswara2008perceptual].   

Despite this compelling theoretical framework, the empirical evidence in favour of the aforementioned claims remains weak and inconsistent [@kaliuzhna2019no; @yang2013visual; @manning2017susceptibility]. One of the possible reason can be found in the methodological difficulties of manipulating illusions in experimental settings and of accurately measuring their effect. Indeed, most conventional illusion paradigms typically focused on participants' subjective perceptions of illusion stimuli. To this end, we implemented an open-source Python software, *Pyllusion*, that would allow us to manipulate the actual parameters of visual illusions [@makowski2021]. In an attempt to address some of the limitations of previous studies [@makowski2022illusion], the objectively parameterized illusory stimuli generated was hence implemented in a new experimental paradigm that allows manipulating various illusory effects in a continuous manner, and measuring the objective behavioural effect (on error rates and response time) of various traditional illusions. Using this *Illusion Game* task, they reported evidence for the existence of a general factor (labelled Factor *i*) to the inter-individual sensitivity to 10 different illusions, as well as relationships with personality traits. However, several limitations were noted, including the potential confounding effect of purely perceptual abilities unrelated to illusion sensitivity *per se*, and the non-inclusion of response times - which could potentially capture different mechanisms related to illusion processing - in the factor analysis.

Using a short version of the *Illusion Game* (made of 3 illusion types), the aim of the present study is to 1) replicate previous findings regarding the common factor of illusion sensitivity and its links with personality, 2) extend these findings to more targeted participant characteristics (such as schizotypal and autistic traits), and 3) test the validity and reliability of the measure using a control task of perceptual discrimination and test-retest protocol.

## Hypotheses

We grouped our hypotheses according to 3 levels of expectation strength (*replication* of [@makowski2022illusion]; *confirmation* of the findings reported by past studies; and *exploration* of potential hypotheses based on theoretical models and assumptions). The null hypothesis (H0) corresponds to no significant effect.

### Replication

#### Psychometry

H1.  **Effect of Illusion Strength and Difficulty**
    -   1.1 *On error rate*
        -   1.1.1 Positive effect of illusion strength on error rate
        -   1.1.2 Positive effect of task difficulty on error rate
    -   1.2 *On RT*
        -   1.2.1 Negative effect of illusion strength on response time
        -   1.2.2 Negative effect of task difficulty on response time
H2.  **General Factor *i***
    -   2.1 Across different illusions, inter-individual illusion scores load onto a unique latent dimension that reflects a general sensitivity to illusions

#### Inter-individual Correlates

H3.  **Normal personality traits**
    -   3.1 Positive correlation between illusion sensitivity and Agreableness
    -   3.2 Positive correlation between illusion sensitivity and Honesty-Humility
H4.  **Maladaptive personality traits**
    -   4.1 Negative correlation between illusion sensitivity and Antagonism
    -   4.2 Negative correlation between illusion sensitivity and Disinhibition
    -   4.3 Negative correlation between illusion sensitivity and Negative Affect
    -   4.4 Negative correlation between illusion sensitivity and Psychoticism

### Confirmation

H5.  **Autism and Schizotypal traits**

Under the predictive coding framework, illusion sensitivity has been theorized to be related to an underweighting of prior knowledge when making perceptual inferences (@notredame2014; @koethe2009binocular. Indeed, this is consistent with findings in which susceptibility to different visual illusions was lower in individuals with a lower competence in contextual integrations, such as those with higher disorganized and positive schizotypal traits [@bressan2021most; @fradkin2022resistance], as well as those with high systemizing tendencies (often associated with autism; @walter2009specific).

-   5.1 Negative correlation between illusion sensitivity and autistic traits, specifically in dimensions related to systemizing tendencies (measured with the *Patterns/Numbers* subscale)
-   5.2 Negative correlation between illusion sensitivity and schizotypal personality traits, particularly in the positive (measured with the *Cognitive-Perceptual* subscale) and disorganized dimensions (measured with the *Disorganized* subscale)

H6.  **Mood and Emotion Regulation**

While the literature regarding the links between emotion and mood dysregulation with illusion sensitivity is sparse, some researchers report higher trait anxiety to be related to reduced illusion sensitivity [@baroun2005; @passie2013impaired]. In fact, consistent with the predictive coding theory, anxiety has been linked to having hyper-precise prior beliefs and a decreased ability to consider contextual information, thereby resulting in individuals creating incoherent percepts that are resistant to belief updating [@passie2013impaired; @hein2021state]. Alternatively, we expect borderline personality traits to correlate negatively with illusion sensitivity due to its association with interoceptive deficits [@flasbeck2020altered]. On the other hand, research on visual illusion sensitivity related to depressive traits have typically not found any significant effects [@koethe2009binocular; @passie2013impaired].

-   6.1 No correlation between illusion sensitivity and depression scores (measured with the *Depression* subscale in the PHQ-4)
-   6.2 Negative correlation between illusion sensitivity and anxiety scores (measured with the *Anxiety* subscale in the PHQ-4)
-   6.2 Positive correlation between illusion sensitivity and borderline personality traits

### Exploration

#### Psychometry

H7.  **Test-retest Reliability**
    -   7.1 Inter-individual illusion scores at time point 1 (*t2*) will correlate significantly with the scores at time point 2 (*t2*)
H8.  **Case-level Estimation Reliability**
    -   8.1 The individual illusion sensitivity scores derived from the population models will strongly correlate with scores estimated by individual models fitted on each participant.
H9.  **Within-participants Stability**
    -   9.1 The inter-individual scores are estimated with a lower uncertainty (95% CI width) than the range (95% ETI) of the point-estimates (i.e., larger between-participants variance than within-participants)
H10.  **Perceptual independence**
    -   10.1 None to weak correlation between illusion sensitivity and perceptual ability

#### Inter-individual Correlates

H11. **Conspiracy Beliefs**

Although little attention has been conferred to investigating the links between conspiracy beliefs and illusion sensitivity, [@van2018connecting] report illusory pattern perception (misperception of meaningful patterns in random stimuli) to be positively linked to greater belief in conspiracy theories, suggesting that individuals with a greater conspiracy mindset may have a greater need to make sense of or impose order of the world and hence may be more aware of external cues, thus influencing their illusion sensitivity. This is in line with [@van2015perceptual], that showed an association between conspiracy beliefs and a stronger local-to-global interference effect (i.e., a difficulty in ignoring irrelevant local visual information when making a decision about the global stimulus features).

-   11.1 Negative correlation between illusion sensitivity and tendency to believe in conspiracies

H12. **Interoception**

Imprecise predictions of internal bodily signals has been associated with an increased reliance on external environmental cues [@synofzik2010misattributions; @seth2012interoceptive], which should translate into a lesser illusion sensitivity of people with lower interoceptive skills. This is in line with with the evidence showing that autism and schizophrenia, in which decreased interoceptive abilities are reported [@notredame2014; @ciszewski2015perception; @park2022; @bolte2007gestalt], are also associated with a lower illusion sensitivity.

-   12.1 Positive correlation between illusion sensitivity and interoceptive abilities

H13. **Lying tendency**

Given the positive relationship observed between illusion sensitivity and honesty-humility, as well as the negative link it shares with maladaptive personality traits [@makowski2022illusion], we expect illusion sensitivity to be associated with other related dimensions, such as dispositional lying tendencies ([@makowski2021structure].

-   13.1 Negative correlation between illusion sensitivity and general dispositional tendency to lie

H14. **Primal beliefs**

Our basic beliefs about the world (i.e., primals) influence the way we interact with it. As such, having greater beliefs that the world is *Safe*, comprehensible (*Understandable*), does not stay static (*Changing*) and that there is an inherent underlying order (*Hierarchical*), may influence people's vigilance towards environmental cues ([@clifton2021brief], and thus be related to illusion sensitivity. This is in line with the negative link found between conspiracy beliefs (which negatively correlates with beliefs of a safe world; [@leone2019moral] and illusory pattern perception [@van2018connecting].

-   14.1 Negative correlation between illusion sensitivity and the tendency to believe that the world is safe (measured with the *Safe* PI-18 subscale)
-   14.2 Negative correlation between illusion sensitivity and the tendency to believe that the world is not static (measured with the *Changing* PI-18 subscale)
-   14.3 Positive correlation between illusion sensitivity and the tendency to believe that the world inherently has an underlying order (measured with the *Hierarchical* PI-18 subscale)
-   14.4 Positive correlation between illusion sensitivity and the tendency to believe that the world is comprehensible (measured with the *Understandable* PI-18 subscale)

# Methods

## Ethics information

This study was approved by the NTU Institutional Review Board (NTU IRB-2022-187) and all procedures performed were in accordance with the ethical standards of the institutional board and with the 1964 Helsinki Declaration. All participants provided their informed consent prior to participation and were incentivized after completing the study.

## Pilot data

10 participants were recruited via the crowd-sourcing platform *Prolific*. The only inclusion criterion specified was a fluent proficiency in English to ensure that the task instructions were well-understood. Participants were rewarded \textsterling 7.50 for completing the task, which took about one hour to finish (session 1 + session 2).

## Procedure


### Illusion Task

Three illusions that were previously found to most strongly contribute to the general Factor *i* were included in this version of the task - namely, Ebbinghaus, Müller-Lyer, and Vertical-Horizontal. The manipulated experimental variables are the *illusion strength* (i.e., the extent to which the surrounding context of targets of each stimulus reinforces the illusion), and the *objective difference* (i.e., the degree of actual difference in physical attributes between the targets of a stimulus).

The task started with 6 training trials per illusion type, followed by a first series of blocks of 64 illusion trials for each illusion type, in which the trial order was randomized. After this first series of illusion blocks has been presented, a different series is presented (with distinct items) a second time. In total, each participant completes 384 illusion trials (2 x 64 x 3), of which the goal was to answer "as fast as possible and without making errors" (an explicit double constraint on the speed-accuracy trade-off). Trials of the same block were separated by a fixation cross (presented for a random duration between 500 - 1000s), that was spatially jittered around the center of the screen (in a radius of a 1 cm), attenuating its usefulness as a potential reference point.

For the purpose of "gamification" (making the task more interesting and generating intrinsic motivation to maximize speed and accuracy), we added a score ($100 - \mu_{RTcorrect} / P_{correct}$), expressed in percentage, at the end of each block.

### Perceptual Task

To confirm that the illusion sensitivity measured by the illusion task is not simply a pure reflection of perceptual abilities, participants were administered a perception task that was largely similar to the Illusion Task, but in which targets were presented without the surrounding context (i.e., without illusions), differing only in terms of their objective difference. For instance, in the case of the Ebbinghaus illusion, 2 circles of different sizes were displayed side by side without the surrounding circles that create the illusion. Each of the 3 illusion types included 64 trials, presented in a randomized order and split into two series, similar to the Illusion Task. In total, each participant completed 192 Perceptual Task trials (2 x 32 x 3). To avoid order effects between the illusion and the perceptual tasks, the order of the tasks was counterbalanced across participants.

### Questionnaires

A series of questionnaires was administered in between the Illusion Task and the Perceptual Task, in a randomized order. We included one attention check item included within all of the questionnaire (e.g., "example 1", "example 2"), with the exception of the PHQ-4 (which only consists of 4 items).

<!-- All scales were presented as described in their validation study (but the Likert ), with the . Visual analog scales, instead of Likert scales with only 2 extreme anchors, were adapted for the MAIA, MSI-BPD, Mini-IPIP6 and IAS-R questionnaires to limit centrality bias. -->


#### Personality

-   The **Mini IPIP6** (Mini International Personality Item Pool; @@sibley2011) measures 6 'normal' personality dimensions (Honesty-Humility, Neuroticism, Extraversion, Agreeableness, Conscientiousness, Openness) with 24 analog scales.
-   The **PID-5-SF** (Personality Inventory for DSM-5 Short Form; @thimm2016personality) measures 5 maladaptive personality traits (disinhibition, antagonism, detachment, negative affect and psychoticism) with 25 4-point Likert scales.

#### Psychopathology

-   The **SPQ-BRU** (Schizotypal Personality Questionnaire - brief revised updated; @davidson2016schizotypal) measures 4 primary schizotypy dimensions (cognitive-perceptual/positive, interpersonal/negative, disorganized and social anxiety) comprised of 9 secondary factors using 32 5-point Likert scales.
-   The **ASQ - Short** (Autism-Spectrum Quotient; @hoekstra2011construction) measures 5 autistic traits (social skills, routine, switching, imagination, numbers/patterns) using 28 4-point Likert scales.
-   The **MSI-BPD** (Mclean Screening Instrument for Borderline Personality Disorder; @zanarini2003screening) measures borderline personality with 10 analog scales [@huczewska2019categorical].
-   The **PHQ-4** (Patient Health Questionnaire; @kroenke2009ultra) assesses anxiety and depression (2 items each) with 5-point Likert scales.

#### Interoception

-   The **MAIA-2** (Multidimensional Assessment of Interoceptive Awareness Version 2; @mehling2018multidimensional) measures 8 facets of interoception (Noticing, Not Distancing, Not Worrying, Attention Regulation, Emotional Awareness, Self-Regulation, Body Listening and Trusting) with 37 analog scales.
-   The **IAS-R** (Interoceptive Accuracy Scale Revised; adapted from [@murphy2020testing], measures 5 factors of bodily perception (Interoception, Nociception, Expulsion, Elimination, Skin) with 18 analog scales.

#### Beliefs and Misbeliefs

-   The **GCB** (Generic Conspiracist Beliefs scale; @brotherton2013measuring) measures 5 aspects related to conspiracy beliefs (Government malfeasance, malevolent global conspiracies, Extraterrestrial cover-up, personal well-being, control of information) using 15 5-point Likert scales.
-   The **PI-18** (Primals Inventory; @clifton2021brief) measures 6 primal beliefs (Safe, Enticing, Alive, Changing, Understandable, Hierarchical) using 32 6-point Likert scale items. The items from the 3 first dimensions can also be pooled to index the highest-order primal belief (Good).
-   The **LIE scale** (Lying Profile Questionnaire; @makowski2021structure) measures 4 dispositional lying dimensions (Ability, Negativity, Contextuality and Frequency) with 16 visual analog scales.

### Session 2

About 2 weeks following their initial participation, participants were invited to complete the Illusion Task again. To balance the duration of session 1, the MAIA-2, MSI-BPD and PI-18 questionnaires were administered during session 2, after the Illusion Task.

## Design Plan

This study has a mixed design with within-subjects repeated measures (for the experimental tasks) and between-subjects analyses. Data collection and analysis will not be performed blind to the conditions of the experiment. The materials and procedure of the experiment will be the same as that of the pilot study (see **Pilot Data** section).

## Sampling plan

Although Bayesian analysis moves the focus away from null-hypothesis testing and towards evidence quantification (for instance, by means of Bayes factors), a frequentist power-analysis was run nonetheless (<https://sample-size.net/correlation-sample-size/>) to provide a lower bound estimate. Using α = .05, β = .2 and the average correlation reported by [@makowski2022illusion] of r = .17, the suggested minimum target sample size was 240 participants. To account for potential outliers, drop-outs and attrition rate (participants that did not participate in session 2), we aim at recruiting 500 participants.

## Analysis Plan

The analysis script is available in ...

Data of participants with outlying scores (in regard to the population distributions) will be further examined and potentially excluded if there is reason to suspect that they did not pay attention to the task (e.g., failing to make the appropriate response to attention check items embedded in questionnaires, the presence of a high number of errors in "easy" trials, as well as a very short total duration, might suggest that participants answered randomly to quickly finish the task). In this study, missing data will be prevented through the implementation of a forced-choice reaction-time behavioural task, in which the trial does not proceed to the next display until participants make a response.

<!-- We will make our statistical inferences and interpretation based on the Bayes Factors (BF). BF values above 3 and below 1/3 will be regarded as sufficient evidence for the alternative and the null hypothesis, otherwise we will interpret the BF as the strength of relative evidence between the hypotheses. -->

# Data Availability

Anonymized data is available at [**https://github.com/RealityBending/IllusionGameReliability**](https://github.com/RealityBending/IllusionGameReliability){.uri}

# Code Availability

The code for the experiment and the analysis is available at https://github.com/RealityBending/IllusionGameReliability


# Acknowledgements

This work was supported by the Presidential Postdoctoral Fellowship Grant (NTU-PPF-2020-10014) from Nanyang Technological University (awarded to DM). The funders have/had no role in study design, data collection and analysis, decision to publish or preparation of the manuscript.

# Author Contributions

The authors made the following contributions. DM: Conceptualization, Data curation, Formal Analysis, Funding acquisition, Investigation, Methodology, Project administration, Resources, Software, Supervision, Validation, Visualization, Writing -- original draft; AST: Project administration, Data curation, Resources, Software, Investigation, Writing -- original draft; SK: Project administration, Resources, Writing -- original draft; NZL: Project administration, Resources, Writing -- review & editing; AC: Project administration, Supervision, Writing -- review & editing.

# Competing Interests

The authors declare no competing interests.

\newpage

# References

::: {#refs custom-style="Bibliography"}
:::

\newpage

# Design Table

```{r echo=FALSE, warning=FALSE}
table <- data.frame(
  Question = "Q1 Replication - Will the results observed from Makowski et al., (under review) be replicated?",
  Hypothesis = "H1.1 - Participants make more errors for high Illusion Strength and Difficulty",
  Sampling = "N=400 * 384 trials",
  Analysis = "The analysis will be similar to that of Makowski et al., (under review). We will use Bayesian mixed models to analyse the relationship between the parametric properties of the visual illusions (i.e., illusion strength and objective difference), and participants’ behavioural reactions i.e., their speed and accuracy in their responses. Error rates will be analyzed using Bayesian logistic mixed models, and RTs of correct responses will be analyzed using an ex-Gaussian family.",
  Interpretation = "Successful replication if greater illusion strength and task difficult is found to lead to a significant increase in error rate and repsonse time."
)


table <- table |>
  rbind(
    list(
      Question = "Q1 Replication",
      Hypothesis = "H1.2 - Participants are slower for high Illusion Strength and Difficulty",
      Sampling = "N=400 * 384 trials",
      Analysis = "See above.",
      Interpretation = "See above."
    ),
    list(
      Question = "Q1 Replication",
      Hypothesis = "H2 - The illusion sensitivity scores for each illusion type will be related to a General Factor *i*",
      Sampling = "N=400",
      Analysis = "Factor analysis and structural equation modeling will be applied on the individual scores derived from the aforementioned models to test the existence of an overarching latent factor.",
      Interpretation = "Successful replication if we found a superior fit for a common factor model against models with only illusion-specific factors."
    ),
    list(
      Question = "Q1 Replication",
      Hypothesis = "H3 - Inter-individual illusion sensitivity will correlate positively with *Agreeableness* and *Honesty-Humility*",
      Sampling = "N=400",
      Analysis = "Using Pearson's test (or Spearman?), correlation analysis will be conducted between participants' general illusion sensitivity and their personality trait scores",
      Interpretation = "Successful replication if we found strong evidence (BF >10) in favor of H3. BF <0.1 will be regarded as strong evidence for the null hypothesis."
    ),
    list(
      Question = "Q1 Replication",
      Hypothesis = "H4 - Inter-individual illusion sensitivity will correlate negatively with *Antagonism*, *Disinhibition*, *Negative Affect* and *Psychoticism*",
      Sampling = "N=400",
      Analysis = "See above.",
      Interpretation = "See above."
    ),
    list(
      Question = "Q2 Confirmation - Will the General Factor *i* correlate in the directions we expect with other measures/variables that assess similar/unrelated constructs?",
      Hypothesis = "H5.1 - Inter-individual illusion sensitivity will correlate negatively with autistic traits, particularly with the systemizing dimensions (measured with the *Patterns/Numbers* subscale in ASQ-short)",
      Sampling = "N=400",
      Analysis = "See above.",
      Interpretation = "Convergent validity for the one-factor solution of illusion sensitivity is supported if we find strong evidence (BF >10) for H5.1. BF <0.1 will be regarded as strong evidence for the null hypothesis."
      ),
    list(
      Question = "Q2 Confirmation",
      Hypothesis = "H5.2 - Inter-individual illusion sensitivity will correlate negatively with schizotypal traits, particularly with the positive and disorganized dimensions (measured with the *Cognitve-Perceptual* and *Disorganized* subscale in the SPQ)",
      Sampling = "N=400",
      Analysis = "See above.",
      Interpretation = "See above."
    ),
    list(
      Question = "Q2 Confirmation",
      Hypothesis = "H6.1 - Inter-individual illusion sensitivity will not correlate negatively with depression scores (meausured with the *Depression* subscale in PHQ-4)",
      Sampling = "N=400",
      Analysis = "See above.",
      Interpretation = "Divergent validity for the one-factor solution of illusion sensitivity is supported if we find strong evidence (BF >10) for H5.1. BF <0.1 will be regarded as strong evidence for the null hypothesis."
    ),
    list(
      Question = "Q2 Confirmation",
      Hypothesis = "H6.2 - Inter-individual illusion sensitivity will correlate negatively with anxiety scores (meausured with the *Anxiety* subscale in PHQ-4)",
      Sampling = "N=400",
      Analysis = "See above.",
      Interpretation = "Convergent validity for the one-factor solution of illusion sensitivity is supported if we find strong evidence (BF >10) for H6.2. BF <0.1 will be regarded as strong evidence for the null hypothesis."
    ),
    list(
      Question = "Q2 Confirmation",
      Hypothesis = "H6.3 - Inter-individual illusion sensitivity will correlate positively with borderline personality traits",
      Sampling = "N=400",
      Analysis = "See above.",
      Interpretation = "See above."
    ),
    list(
      Question = "Q3 Psychomtery - Will the General Illusion Sensitivty one-factor solution  found demonstrate adequate psychometric properties? ",
      Hypothesis = "H7 - Inter-individual illusion scores at time point 1 (*t2*) will correlate significantly with the scores at time point 2 (t2*) ",
      Sampling = "N=400",
      Analysis = "Correlation analysis will be conducted between illusion scores at *t1* and *t2* to assess the test-retest reliabiltiy of the General Illusion Sensitivity Factor *i*",
      Interpretation = "Factor *i* is regarded as reliable if we find strong evidence (BF >10) for H5.1. BF <0.1 will be regarded as strong evidence for the null hypothesis."
    ),
    list(
      Question = "Q3 Psychometry",
      Hypothesis = "H8 - The individual illusion sensitivity scores derived from the population models will strongly correlate with scores estimated by individual models fitted on each participant",
      Sampling = "N=400",
      Analysis = "Correlation analysis will be conducted between individual illusion scores derived from population models and that derived from individual models to assess case-level estimation reliability of the Factor *i*",
      Interpretation = "See above."
    ),
    list(
      Question = "Q3 Psychometry",
      Hypothesis = "H9 - The variability in inter-individual illusion scores will be larger than the variability in indiviudal illusion scores (i.e., larger between-participants variance than within-participants)",
      Sampling = "N=400",
      Analysis = "The width of the confidence intevals (95% CI width) of inter-individual illusion scores will be compared with the range of the point-estimates (95% ETI)",
      Interpretation = "Factor *i* is regarded as being stable within individuals if we find strong evidence (BF >10) for H9. BF <0.1 will be regarded as strong evidence for the null hypothesis."
    ),
    list(
      Question = "Q3 Psychometry",
      Hypothesis = "H10 - There will be none or weak correlation between individuals' general illusion sensitivity and perceptual ability ",
      Sampling = "N=400",
      Analysis = "Correlation analysis will be conducted between individuals' illusion sensitivity scores and their perceptual task scores",
      Interpretation = "Factor *i* is regarded as distinct from pure perceptual ability if we find strong evidence (BF >10) for H10. BF <0.1 will be regarded as strong evidence for the null hypothesis."
    ),
    list(
      Question = "Q4 Conspiracy Beliefs - Will individuals' general illusion sensitivity correlate with their beliefs in conspiracy theories?",
      Hypothesis = "H11 - Inter-individual illusion sensitivity will correlate negatively with tendency to believe in conspiracies",
      Sampling = "N=400",
      Analysis = "correlation analysis will be conducted between participants' general illusion sensitivity and their GCBS scores",
      Interpretation = "H11 is supported if we find strong evidence (BF >10) in favor of it. BF <0.1 will be regarded as strong evidence for the null hypothesis."
    ),
    list(
      Question = "Q5 Interoception - Will individuals' general illusion sensitivity correlate with interoception?",
      Hypothesis = "H12 - Inter-individual illusion sensitivity will correlate positively with interoceptive abilities",
      Sampling = "N=400",
      Analysis = "See above.",
      Interpretation = "See above."
    ),
    list(
      Question = "Q6 Lying Tendency - Will individuals' general illusion sensitivity correlate with their dispositional tendency to lie?",
      Hypothesis = "H13 - Inter-individual illusion sensitivity will correlate negatively with general dispositonal tendency to lie",
      Sampling = "N=400",
      Analysis = "See above.",
      Interpretation = "See above."
    ),
    list(
      Question = "Q7 Primal Beliefs - Will individuals' general illusion sensitivity correlate with their basic beliefs about the world? ",
      Hypothesis = "H14.1 - Inter-individual illusion sensitivity will correlate negatively with the tendency to believe that the world is safe (measured with the *Safe* subscale in PI-18)",
      Sampling = "N=400",
      Analysis = "See above.",
      Interpretation = "See above."
    ),
    list(
      Question = "Q7 Primal Beliefs",
      Hypothesis = "H14.2 - Inter-individual illusion sensitivity will correlate negatively with the tendency to believe that the world is not static (measured with the *Changing* subscale in PI-18)",
      Sampling = "N=400",
      Analysis = "See above.",
      Interpretation = "See above."
    ),
    list(
      Question = "Q7 Primal Beliefs",
      Hypothesis = "H14.3 - Inter-individual illusion sensitivity will correlate positively with the tendency to believe that the world inherently has an underlying order (measured with the *Hierarchical* subscale in PI-18)",
      Sampling = "N=400",
      Analysis = "See above.",
      Interpretation = "See above."
    ),
    list(
      Question = "Q7 Primal Beliefs",
      Hypothesis = "H14.4 - Inter-individual illusion sensitivity will correlate positively with the tendency to believe that the world is comprehensible (measured with the *Understandable* subscale in PI-18)",
      Sampling = "N=400",
      Analysis = "See above.",
      Interpretation = "See above."
    ))


    

knitr::kable(table)



# Question <- c(
#   "Is illusion sensitivity more stable within individuals than between them?",
#   "Is illusion sensitivity distinct from pure perceptual ability?",
#   "Does illusion sensitivity correlate with the HEXACO personality traits, specifically in the dimensions of Agreeableness and Honesty-Humility?",
#   "Does illusion sensitivity correlate with the PID-5 maladaptive personality traits, speicifically in the dimensions of Antagonism, Disinhibition, Negative Affect and Psychoticism",
#   "Does illusion sensitivity correlate with autistic traits, specifically in the dimensions related to systemizing tendencies?",
#   "Does illusion sensitivity correlate with schizotypal traits, specifically in the cognitive-perceptual and disorganzied dimensions?",
#   "Does illusion sensitivtiy correlate with trait depression levels?",
#   "Does illusion sensitivity correlate with trait anxiety levels?",
#   "Does illusion sensitivity correlate with borderline personality traits?",
#   "Does illusion sensitivity correlate with conspiracy beliefs?",
#   "Does illusion sensitivtiy correlate with interoception?",
#   "Does illusion sensitivtiy correlate with dispositional lying tendencies?",
#   "Does illusion sensitivity correlate with primal beliefs, specifically in the beliefs of the world being safe, hierarchical, understandable and changing?"
# )
# 
# Hypothesis <- c(
#   "Participants will make more errors when the illusion strength is greater (H1.1.1)",
#   "Participants will make more errors when the task difficulty is higher (H1.1.2)",
#   "Participants will take a shorter time to respond when the illusion strength is greater (H1.2.1)",
#   "Participants will take a shorter time to respond when the task difficulty is higher (H1.2.2)",
#   "Across different illusions, inter-individual illusion scores will load onto a unique latent dimension that reflects a general sensitivity to illusions (H2)",
#   "Participants' illusion sensitivity (measured using illusion scores calculated by assessing the inter-individual variability in the effect of illusion strength and its interaction with task difficulty) at time point 1 (t1) will correlate significantly with the illusion sensitivty found at time point 2 (t2, which takes place two weeks later) (H3)",
#   "There will be a larger betweeen-participant variance in illusion sensitivity than within-participants. (H4)",
#   "Participants' intra-individual illusion sensitivity will not correlate significantly with their objective perceptual ability (H5)",
#   "Participants with greater illusion sensitivity will score higher on Agreeableness (measured using the Mini-IPIP scale) (H6.1)",
#   "Participants with greater illusion sensitivity will score higher on Honesty-Humility (meausured using the Mini-IPIP scale) (H6.2)",
#   "Participants with greater illusion sensitivity will score lower on Antagonism (measured using the PID-5 scale) (H7.1)",
#   "Participants with greater illusion sensitivity will score lower on Disinhibition (measured using the PID-5 scale) (H7.2)",
#   "Participants with greater illusion sensitivity will score lower on Negative Affect (measured using the PID-5 scale) (H7.3)",
#   "Participants with greater illusion sensitivity will score lower on Psychoticism (measured using the PID-5 scale) (H7.4)",
#   "Participants with lower illusion sensitivity will exhibit more autistic traits, particularly in the dimensions related to systemizing tendencies (measured using the Patterns/Numbers subscale in ASQ-Short) (H8.1)",
#   "Participants with lower illusion sensitivity will exhibit more schizotypal personality traits, particularly in the positive (measured using the Cognitive-Perceptual subscale in SPQ) and disorganized dimensions (measured with the Disorganized subscale in SPQ) (H8.2)",
#   "Participants with lower illusion sensitivity will display higher levels of depression (measured using the Depression subscale in the PHQ-4) (H9.1)",
#   "Participants' illusion sensitivity will not have any significant associations with their level of anxiety (measured using the Anxiety subscale in the PHQ-4) (H9.2)",
#   "Participants with higher illusion sensitivity will exhibit more borderline personality traits (measured using the MSI-BPD) (H9.3)",
#   "Participants with lower illusion sensitivity will exhibit a greater tendency to believe in conpiracies (measured using the GCBS) (H10)",
#   "Participants with greater illusion sensitivity will have better interoceptive abilities (measured using the IAS-R and MAIA-2) (H11)",
#   "Participants with higher illusion sensitivity will exhibit a lower dispositional tendency to lie (measured using The LIE Scale) (H12)",
#   "Participants with lower illusion sensitivity will exhibit a higher tendency to believe that the world is safe (measured using the Safe subscale in PI-18) (H13.1)",
#   "Participants with lower illusion sensitivity will exhibit a higher tendency to believe that the world is not static (measured using the Changing subscale in PI-18) (H13.2)",
#   "Participants with higher illusion sensitivity will exhibit a higher tendency to believe that the world is inherently has an underlying order (measured using the Hierarchical subscale in PI-18) (H13.3)",
#   "Participants with higher illusion sensitivity will exhibit a higher tendency to believe that the world is comprehensible (measured with the Understandable subscale in PI-18) (H13.4)"
# )
# 
# Sampling_Plan <- c(
#   "Using a two-sided 5% significance level test (α=0.05) with power 80% power (β=0.2), the required sample size to detect a correlation r=0.17 is 240. To account for expected drop-outs, attrition rate and outliers due to poor data quality based on prior research sampling conducted on online platforms ([Palan & Schitter, 2018](https://doi.org/10.1016/j.jbef.2017.12.004)); [Peer et al., 2022](10.3758/s13428-021-01694-3)), we will target to recruit 400 participants.",
#   "N=400",
#   "N=400",
#   "N=400",
#   "N=400",
#   "N=400",
#   "N=400",
#   "N=400",
#   "N=400",
#   "N=400",
#   "N=400",
#   "N=400",
#   "N=400",
#   "N=400",
#   "N=400",
#   "N=400"
# )
# 
# Analysis_Plan <- c(
#   "We will use Bayesian mixed models to analyse the relationship between the parametric properties of the visual illusions (i.e., illusion strength and objective difference), and participants’ behavioural reactions i.e., their speed and accuracy in their responses. Error rates will be analyzed using Bayesian logistic mixed models, and RTs of correct responses will be analyzed using an ex-Gaussian family.",
#   "We will extract inter-individual variance in the effect of illusion strength and its interaction with task difficulty from models as participant-level scores and conduct Structural Equation Modelling (SEM) as well as Confirmatory Factor Analysis (CFA) to test for the existence of a general factor of illusion sensitivity",
#   "A correlation analysis will be conducted across participants to assess the test-retest reliabiltiy of the intra-individual illusion sensitvity factor found",
#   "We will compare the width of the confidence intevals (95% CI width) of illusion scores with the range of the point-estimates (95% ETI)",
#   "We will assess the correlation between participants' illusion scores with their objective perceptual task scores using Pearson's test (or Spearman ???)",
#   "As above",
#   "As above",
#   "As above",
#   "As above",
#   "As above",
#   "As above",
#   "As above",
#   "As above",
#   "As above",
#   "As above",
#   "As above"
# )
# 
# Interpretation <- c(
#   "If greater illusion strength and task difficult is found to lead to a significant increase in error rate and repsonse time, we will interpret that there is sufficient evidence to claim that the results of the previous Illusion Game study was successfully replicated",
#   "",
#   "If the correlation between illusion sensitivty measured two weeks apart is found to be significant, we will interpret that there is sufficient evidence to claim that illusion sensitivty is reliable across time",
#   "If participants' illusion scores are estimated with a lower uncertainty (95% CI width) than the range (95% ETI) of the point-estimates (i.e., larger between-participants variance than within-participants), we will interpret that there is sufficient evidence to claim that illusion sensitivity is more stable within participants than between participants",
#   "If participants' illusion scores do not significantly correlate with their perceptual task scores, we will interpret that illusion sensitivity is distinct from pure perceptual ability",
#   "if participants' illusion sensitivty is found to significantly positiviely correlate with their scores in Agreeableness and/or Honesty-Humility, we will interpret that there is sufficient evidence to claim that  people with greater illusion sensitivty are more likely to have higher scores in the correespondiong HEXACO traits",
#   "if participants' illusion sensitivty is found to significantly negatively correlate with their scores in Antagonism, Disinhibition, Negative Affect and/or Psychoticism, we will interpret that there is sufficient evidence to claim that  people with greater illusion sensitivty are more likely to have lower scores in the corresponding maladaptive traits",
#   "As Above",
#   "As Above",
#   "As Above",
#   "If participants' illusion sensitivity is not found to correlate significantly with their levels of anxiety, we will interpret that there is sufficient eviedence to claim that illusion sensitivity is significantly not associated with trait anxiety",
#   "if participants' illusion sensitivty is found to significantly positiviely correlate with their scores in MSI-BPD, we will interpret that there is sufficient evidence to conclude that people with higher illusion sensitivity are more likely to exhibit borderline personality traits",
#   "if participants' illusion sensitivty is found to significantly negatively correlate with their scores in GCBS, we will interpret that there is sufficient evidence to claim that people with greater illusion sensitivty are more likely to have less conspiracy beliefs",
#   "if participants' illusion sensitivty is found to significantly positiviely correlate with their scores in interoception, we will interpret that there is sufficient evidence to claim that  people with greater illusion sensitivty are more likely to have better interoceptive abilities",
#   "if participants' illusion sensitivty is found to significantly negatively correlate with their scores in the LIE scale, we will interpret that there is sufficient evidence to claim that people with greater illusion sensitivty are likely to exhibit a tendency to lie",
#   "If participants' illusion sensitivty is found to significantly positively correlate with their scores in the Safe and/or Changing subscales of the PI-18, we will interpret that there is sufficient evidence to claim that people with greater illusion sensitivty are more likely to exhibit the corresponding primal beliefs. If participants' illusion sensitivty is found to significantly negatively correlate with their scores in the Hierarchical and/or Understandable subscales of the PI-18, we will interpret that there is sufficient evidence to claim that people with greater illusion sensitivty are less likely to exhibit the corresponding primal beliefs"
# )
# 
# Rationale <- c(
#   "We will make our statistical inferences and interpretation based on the Bayes Factors (BF). BF values above 3 and below 1/3 will be regarded as sufficient evidence for the alternative and the null hypothesis, otherwise we will interpret the BF as the strength of relative evidence between the hypotheses.",
#   "As Above",
#   "As Above",
#   "As Above",
#   "As Above",
#   "As Above",
#   "As Above",
#   "As Above",
#   "As Above",
#   "As Above",
#   "As Above",
#   "As Above",
#   "As Above",
#   "As Above",
#   "As Above",
#   "As Above"
# )
# 
# 
# design_table <- tibble::tribble(
#   ~Question, ~Hypothesis, ~Sampling_Plan, ~Analysis_Plan, ~Interpretation, ~Rationale, Question[1], Hypothesis[1:4], Sampling_Plan[1], Analysis_Plan[1], Interpretation[1], Rationale[1],
#   Question[2], Hypothesis[5], Sampling_Plan[2], Analysis_Plan[2], Interpretation[2], Rationale[2],
#   Question[3], Hypothesis[6], Sampling_Plan[3], Analysis_Plan[3], Interpretation[3], Rationale[3],
#   Question[4], Hypothesis[7], Sampling_Plan[4], Analysis_Plan[4], Interpretation[4], Rationale[4],
#   Question[5], Hypothesis[8], Sampling_Plan[5], Analysis_Plan[5], Interpretation[5], Rationale[5],
#   Question[6], Hypothesis[9:10], Sampling_Plan[6], Analysis_Plan[6], Interpretation[6], Rationale[6],
#   Question[7], Hypothesis[11:14], Sampling_Plan[7], Analysis_Plan[7], Interpretation[7], Rationale[7],
#   Question[8], Hypothesis[15], Sampling_Plan[8], Analysis_Plan[8], Interpretation[8], Rationale[8],
#   Question[9], Hypothesis[16], Sampling_Plan[9], Analysis_Plan[9], Interpretation[9], Rationale[9],
#   Question[10], Hypothesis[17], Sampling_Plan[10], Analysis_Plan[10], Interpretation[10], Rationale[10],
#   Question[11], Hypothesis[18], Sampling_Plan[11], Analysis_Plan[11], Interpretation[11], Rationale[11],
#   Question[12], Hypothesis[19], Sampling_Plan[12], Analysis_Plan[12], Interpretation[12], Rationale[12],
#   Question[13], Hypothesis[20], Sampling_Plan[13], Analysis_Plan[13], Interpretation[13], Rationale[13],
#   Question[14], Hypothesis[21], Sampling_Plan[14], Analysis_Plan[14], Interpretation[14], Rationale[14],
#   Question[15], Hypothesis[22], Sampling_Plan[15], Analysis_Plan[15], Interpretation[15], Rationale[15],
#   Question[16], Hypothesis[23:26], Sampling_Plan[16], Analysis_Plan[16], Interpretation[16], Rationale[16]
# )
# 
# 
# 
# 
# names(design_table) <- c("Question", "Hypothesis", "Sampling Plan", "Analysis Plan", "Interpretation", "Rationale for Sensitivity of Test")
# 
# knitr::kable(design_table)
```
